// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './index'

export type PageName = 'Adapter/Form' | 'Adapter/HeadKeys' | 'Adapter/InfiniteReverse' | 'Home' | 'Users/Index' | 'Users/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Adapter/Form': unknown
    'Adapter/HeadKeys': unknown
    'Adapter/InfiniteReverse': unknown
    'Home': unknown
    'Users/Index': unknown
    'Users/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
